### ISSUE TITLE
Hashbang detection when sharing URL

### ISSUE THREAD

**Issue by IngwiePhoenix** [bytecipher/grapnel#52]
When client A uses a browser that does not support the `pushState` mechanism, they may link the URL to another user to share it. That user then opens the URL - but from hat I can see in the code, the hashbang is not checked for, only i the mode is set to be the hashchange one.

Client A: http://example.com/#!one/route
Client B: http://example.com/one/route

Client B can share URL with client A - but possibly not vice versa.

A "if hashbang available, open that route" kind of fallback would be nice. :)

**Comment by bytecipher** [comment]
This is the downfall of the front-end router. There are solutions to this, but none of them are unobtrusive. However, since Grapnel supports multiple routers, you could do something like this:


```javascript
var regularRouter = new Grapnel({ pushState: true }),
    hashBangrouter = new Grapnel({ hashBang: true });

regularRouter.add = function(){
    hashBangrouter.add.apply(this, arguments);
    Grapnel.prototype.add.apply(this, arguments);
}

regularRouter.get('/one/route', function(req){
    // Do stuff
});
```

I have not tested this, but it should work. Either way, you get the idea. It basically allows you to add routes using the `regularRouter` pushState router and have them automatically listen for hashBang routes of the same path.

Hope this helps! @IngwiePhoenix

**Comment by IngwiePhoenix** [comment]
Thank you! I am so sorry I replied that late.

But this is pretty much what I was lookng for :)
